version: '3.8'

services:

  client:
    image: dolphintellect-client:latest
    ports:
      - "8989:80"
    container_name: dolphintellect-client
    depends_on:
      - dolphintellect-api
    networks:
      - mynetwork


  dolphintellect-api:
    build: .
    image: dolphintellect-api:latest
    ports:
      - "8081:8080"
    networks:
      - mynetwork
    container_name: dolphintellect-container
    depends_on:
      mysql_container:
        condition: service_healthy
      neo4jcontainer:
        condition: service_healthy



  neo4jcontainer:
    container_name: dolphintellect_neo4j
    image: neo4j:latest
    ports:
      - "7475:7474"
      - "7688:7687"
    networks:
      - mynetwork
    environment:
      - NEO4J_AUTH=neo4j/password
#    env_file:
#      - .env
#    environment:
#      - NEO4J_AUTH=${NEO4JUSER}/${NEO4JPASSWORD}
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s

  mysql_container:
    container_name: dolphintellect_mysql
    image: mysql
    restart: always
    ports:
        - "3307:3306"
    networks:
      - mynetwork
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: dolphintellect
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  mynetwork:
    driver: bridge